services:
  - type: web
    name: uyisenganimanzi
    env: node
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    autoDeploy: true
