/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as AboutTeamRouteImport } from './routes/about.team'
import { Route as AboutMissionVisionRouteImport } from './routes/about.mission-vision'
import { Route as AboutImpactRouteImport } from './routes/about.impact'
import { Route as AboutBeneficiariesRouteImport } from './routes/about.beneficiaries'
import { Route as AboutApproachRouteImport } from './routes/about.approach'

const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRoute,
} as any)
const AboutTeamRoute = AboutTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AboutRoute,
} as any)
const AboutMissionVisionRoute = AboutMissionVisionRouteImport.update({
  id: '/mission-vision',
  path: '/mission-vision',
  getParentRoute: () => AboutRoute,
} as any)
const AboutImpactRoute = AboutImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => AboutRoute,
} as any)
const AboutBeneficiariesRoute = AboutBeneficiariesRouteImport.update({
  id: '/beneficiaries',
  path: '/beneficiaries',
  getParentRoute: () => AboutRoute,
} as any)
const AboutApproachRoute = AboutApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => AboutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRoute
  '/programs': typeof ProgramsRoute
  '/about/approach': typeof AboutApproachRoute
  '/about/beneficiaries': typeof AboutBeneficiariesRoute
  '/about/impact': typeof AboutImpactRoute
  '/about/mission-vision': typeof AboutMissionVisionRoute
  '/about/team': typeof AboutTeamRoute
  '/about/': typeof AboutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRoute
  '/programs': typeof ProgramsRoute
  '/about/approach': typeof AboutApproachRoute
  '/about/beneficiaries': typeof AboutBeneficiariesRoute
  '/about/impact': typeof AboutImpactRoute
  '/about/mission-vision': typeof AboutMissionVisionRoute
  '/about/team': typeof AboutTeamRoute
  '/about': typeof AboutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRoute
  '/programs': typeof ProgramsRoute
  '/about/approach': typeof AboutApproachRoute
  '/about/beneficiaries': typeof AboutBeneficiariesRoute
  '/about/impact': typeof AboutImpactRoute
  '/about/mission-vision': typeof AboutMissionVisionRoute
  '/about/team': typeof AboutTeamRoute
  '/about/': typeof AboutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/get-involved'
    | '/programs'
    | '/about/approach'
    | '/about/beneficiaries'
    | '/about/impact'
    | '/about/mission-vision'
    | '/about/team'
    | '/about/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/gallery'
    | '/get-involved'
    | '/programs'
    | '/about/approach'
    | '/about/beneficiaries'
    | '/about/impact'
    | '/about/mission-vision'
    | '/about/team'
    | '/about'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/get-involved'
    | '/programs'
    | '/about/approach'
    | '/about/beneficiaries'
    | '/about/impact'
    | '/about/mission-vision'
    | '/about/team'
    | '/about/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  ProgramsRoute: typeof ProgramsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/team': {
      id: '/about/team'
      path: '/team'
      fullPath: '/about/team'
      preLoaderRoute: typeof AboutTeamRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/mission-vision': {
      id: '/about/mission-vision'
      path: '/mission-vision'
      fullPath: '/about/mission-vision'
      preLoaderRoute: typeof AboutMissionVisionRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/impact': {
      id: '/about/impact'
      path: '/impact'
      fullPath: '/about/impact'
      preLoaderRoute: typeof AboutImpactRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/beneficiaries': {
      id: '/about/beneficiaries'
      path: '/beneficiaries'
      fullPath: '/about/beneficiaries'
      preLoaderRoute: typeof AboutBeneficiariesRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/approach': {
      id: '/about/approach'
      path: '/approach'
      fullPath: '/about/approach'
      preLoaderRoute: typeof AboutApproachRouteImport
      parentRoute: typeof AboutRoute
    }
  }
}

interface AboutRouteChildren {
  AboutApproachRoute: typeof AboutApproachRoute
  AboutBeneficiariesRoute: typeof AboutBeneficiariesRoute
  AboutImpactRoute: typeof AboutImpactRoute
  AboutMissionVisionRoute: typeof AboutMissionVisionRoute
  AboutTeamRoute: typeof AboutTeamRoute
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutApproachRoute: AboutApproachRoute,
  AboutBeneficiariesRoute: AboutBeneficiariesRoute,
  AboutImpactRoute: AboutImpactRoute,
  AboutMissionVisionRoute: AboutMissionVisionRoute,
  AboutTeamRoute: AboutTeamRoute,
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  ProgramsRoute: ProgramsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
